// <auto-generated />
using System;
using Hostingaffe.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Hostingaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HostingaffeDbContext))]
    [Migration("20260906172342_TheMachine")]
    partial class TheMachine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hostingaffe.Domain.History.HistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_history");

                    b.HasIndex("Subject", "SubjectId", "Id")
                        .HasDatabaseName("history_subject");

                    b.ToTable("history", null, t =>
                        {
                            t.HasCheckConstraint("ck_history_subject", "subject in ('page', 'machine')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.AgentMetadataReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.HasKey("Id")
                        .HasName("pk_identity_metadata");

                    b.HasIndex("IdentityId", "ReportedAt")
                        .HasDatabaseName("identity_metadata_identity");

                    b.ToTable("identity_metadata", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.BrowserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_browser_session");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("browser_session_hash");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("browser_session_user");

                    b.ToTable("browser_session", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Administrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("administrator");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_identity");

                    b.ToTable("identity", null, t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");

                            t.HasCheckConstraint("ck_identity_user", "kind = 'user' and email is not null and normalized_email is not null and user_state in ('invited', 'active', 'deactivated') or kind = 'agent' and email is null and normalized_email is null and user_state is null and password_hash is null and bootstrap_exchanged_at is null");
                        });

                    b.HasDiscriminator<string>("kind").HasValue("Identity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.OneTimeSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("text")
                        .HasColumnName("pending_email");

                    b.Property<string>("PendingNormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("pending_normalized_email");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_one_time_secret");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("one_time_secret_hash");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("one_live_secret_per_purpose")
                        .HasFilter("used_at is null");

                    b.ToTable("one_time_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_one_time_secret_pending_email", "(purpose = 'email_change') = (pending_email is not null)");

                            t.HasCheckConstraint("ck_one_time_secret_purpose", "purpose in ('invitation', 'password_recovery', 'email_change')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_token");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("token_agent")
                        .HasFilter("kind = 'agent'");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("token_secret_hash");

                    b.ToTable("token", null, t =>
                        {
                            t.HasCheckConstraint("ck_token_kind", "kind in ('user', 'agent')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Machines.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Arch")
                        .HasColumnType("text")
                        .HasColumnName("arch");

                    b.Property<string>("Cpu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cpu");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Disk")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("disk");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hostname");

                    b.Property<string>("Ipv4")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipv4");

                    b.Property<string>("Ipv6")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipv6");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<string>("Memory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Os")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("os");

                    b.Property<string>("Plan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plan");

                    b.Property<string>("PrivateIp")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("private_ip");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider");

                    b.Property<string>("Ssh")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ssh");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_machine");

                    b.HasIndex("HostId")
                        .HasDatabaseName("machine_host");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("machine_key");

                    b.ToTable("machine", null, t =>
                        {
                            t.HasCheckConstraint("ck_machine_arch", "arch is null or arch in ('amd64', 'arm64')");

                            t.HasCheckConstraint("ck_machine_host", "host_id is null and kind <> 'vm' or kind = 'vm'");

                            t.HasCheckConstraint("ck_machine_kind", "kind in ('vps', 'dedicated', 'vm', 'local')");

                            t.HasCheckConstraint("ck_machine_not_its_own_host", "host_id is null or host_id <> id");

                            t.HasCheckConstraint("ck_machine_status", "status in ('planned', 'active', 'retired')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Pages.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('simple', title || ' ' || body)", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_page");

                    b.HasIndex("Search")
                        .HasDatabaseName("page_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("page_slug");

                    b.ToTable("page", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("IdentityId", "Key")
                        .HasName("pk_idempotency");

                    b.ToTable("idempotency", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Agent", b =>
                {
                    b.HasBaseType("Hostingaffe.Domain.Identities.Identity");

                    b.Property<DateTimeOffset?>("MetadataReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_reported_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");

                            t.HasCheckConstraint("ck_identity_user", "kind = 'user' and email is not null and normalized_email is not null and user_state in ('invited', 'active', 'deactivated') or kind = 'agent' and email is null and normalized_email is null and user_state is null and password_hash is null and bootstrap_exchanged_at is null");
                        });

                    b.HasDiscriminator().HasValue("agent");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.User", b =>
                {
                    b.HasBaseType("Hostingaffe.Domain.Identities.Identity");

                    b.Property<DateTimeOffset?>("BootstrapExchangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bootstrap_exchanged_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_state");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("identity_email")
                        .HasFilter("kind = 'user'");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");

                            t.HasCheckConstraint("ck_identity_user", "kind = 'user' and email is not null and normalized_email is not null and user_state in ('invited', 'active', 'deactivated') or kind = 'agent' and email is null and normalized_email is null and user_state is null and password_hash is null and bootstrap_exchanged_at is null");
                        });

                    b.HasDiscriminator().HasValue("user");
                });

            modelBuilder.Entity("Hostingaffe.Domain.History.HistoryEntry", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_history_actor");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.AgentMetadataReport", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Agent", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_identity_metadata_identity");

                    b.OwnsOne("Hostingaffe.Domain.Identities.AgentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("AgentMetadataReportId");

                            b1.Property<string>("Environment")
                                .HasJsonPropertyName("environment");

                            b1.Property<string>("Harness")
                                .HasJsonPropertyName("harness");

                            b1.Property<string>("Kind")
                                .HasJsonPropertyName("kind");

                            b1.Property<string>("Version")
                                .HasJsonPropertyName("version");

                            b1.HasKey("AgentMetadataReportId");

                            b1.ToTable("identity_metadata");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentMetadataReportId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.BrowserSession", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_browser_session_user");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.OneTimeSecret", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_one_time_secret_user");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Token", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_token_identity");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Machines.Machine", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_machine_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_machine_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Machines.Machine", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_machine_host");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_machine_updated_by");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Pages.Page", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_page_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_page_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_page_updated_by");
                });

            modelBuilder.Entity("Hostingaffe.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_identity");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Agent", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_identity_owner");

                    b.OwnsOne("Hostingaffe.Domain.Identities.AgentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("AgentId");

                            b1.Property<string>("Environment")
                                .HasJsonPropertyName("environment");

                            b1.Property<string>("Harness")
                                .HasJsonPropertyName("harness");

                            b1.Property<string>("Kind")
                                .HasJsonPropertyName("kind");

                            b1.Property<string>("Version")
                                .HasJsonPropertyName("version");

                            b1.HasKey("AgentId");

                            b1.ToTable("identity");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
