// <auto-generated />
using System;
using Hostingaffe.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Hostingaffe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HostingaffeDbContext))]
    [Migration("20260911124909_TheFileASecretLiesIn")]
    partial class TheFileASecretLiesIn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hostingaffe.Domain.AssignedKey", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.HasKey("Kind", "Key")
                        .HasName("pk_assigned_key");

                    b.ToTable("assigned_key", null, t =>
                        {
                            t.HasCheckConstraint("ck_assigned_key_kind", "kind in ('machine', 'software', 'installation')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("note");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Ref")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ref");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('simple', version || ' ' || coalesce(\"ref\", '') || ' ' || coalesce(ticket, '') || ' ' || note)", true);

                    b.Property<string>("Ticket")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ticket");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deployment");

                    b.HasIndex("Search")
                        .HasDatabaseName("deployment_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.HasIndex("InstallationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("deployment_number");

                    b.HasIndex("InstallationId", "At", "Number")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("deployment_when");

                    b.ToTable("deployment", null, t =>
                        {
                            t.HasCheckConstraint("ck_deployment_number", "number >= 1");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Files.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Directory")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("directory");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('simple', path)", true);

                    b.HasKey("Id")
                        .HasName("pk_file");

                    b.HasIndex("Search")
                        .HasDatabaseName("file_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.HasIndex("InstallationId", "Path")
                        .IsUnique()
                        .HasDatabaseName("file_on_installation")
                        .HasFilter("installation_id is not null");

                    b.HasIndex("MachineId", "Path")
                        .IsUnique()
                        .HasDatabaseName("file_on_machine")
                        .HasFilter("machine_id is not null");

                    b.ToTable("file", null, t =>
                        {
                            t.HasCheckConstraint("ck_file_directory", "directory is null or machine_id is not null");

                            t.HasCheckConstraint("ck_file_owner", "num_nonnulls(machine_id, installation_id) = 1");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.History.HistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_history");

                    b.HasIndex("Subject", "SubjectId", "Id")
                        .HasDatabaseName("history_subject");

                    b.ToTable("history", null, t =>
                        {
                            t.HasCheckConstraint("ck_history_subject", "subject in ('page', 'machine', 'software', 'installation', 'file', 'deployment')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.AgentMetadataReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.HasKey("Id")
                        .HasName("pk_identity_metadata");

                    b.HasIndex("IdentityId", "ReportedAt")
                        .HasDatabaseName("identity_metadata_identity");

                    b.ToTable("identity_metadata", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.BrowserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_browser_session");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("browser_session_hash");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("browser_session_user");

                    b.ToTable("browser_session", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.DeviceLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeniedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("denied_at");

                    b.Property<byte[]>("DeviceCodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("device_code_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("IssuedTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_token_id");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("user_code");

                    b.HasKey("Id")
                        .HasName("pk_device_login");

                    b.HasIndex("DeviceCodeHash")
                        .IsUnique()
                        .HasDatabaseName("device_login_code_hash");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("device_login_user_code")
                        .HasFilter("approved_at is null and denied_at is null");

                    b.ToTable("device_login", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Administrator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("administrator");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_identity");

                    b.ToTable("identity", null, t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");

                            t.HasCheckConstraint("ck_identity_user", "kind = 'user' and email is not null and normalized_email is not null and user_state in ('invited', 'active', 'deactivated') or kind = 'agent' and email is null and normalized_email is null and user_state is null and password_hash is null and bootstrap_exchanged_at is null");
                        });

                    b.HasDiscriminator<string>("kind").HasValue("Identity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.OneTimeSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PendingEmail")
                        .HasColumnType("text")
                        .HasColumnName("pending_email");

                    b.Property<string>("PendingNormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("pending_normalized_email");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_one_time_secret");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("one_time_secret_hash");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("one_live_secret_per_purpose")
                        .HasFilter("used_at is null");

                    b.ToTable("one_time_secret", null, t =>
                        {
                            t.HasCheckConstraint("ck_one_time_secret_pending_email", "(purpose = 'email_change') = (pending_email is not null)");

                            t.HasCheckConstraint("ck_one_time_secret_purpose", "purpose in ('invitation', 'password_recovery', 'email_change')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.HasKey("Id")
                        .HasName("pk_token");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("token_agent")
                        .HasFilter("kind = 'agent'");

                    b.HasIndex("SecretHash")
                        .IsUnique()
                        .HasDatabaseName("token_secret_hash");

                    b.ToTable("token", null, t =>
                        {
                            t.HasCheckConstraint("ck_token_kind", "kind in ('user', 'agent')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Installations.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Backup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backup");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Data")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Logging")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logging");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<string>("Monitoring")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("monitoring");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("path");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('simple', key || ' ' || name || ' ' || coalesce(path, '') || ' ' || coalesce(data, '') || ' ' || words(urls) || ' ' || description)", true);

                    b.Property<Guid>("SoftwareId")
                        .HasColumnType("uuid")
                        .HasColumnName("software_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.PrimitiveCollection<string[]>("Urls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValue(new string[0])
                        .HasColumnName("urls");

                    b.HasKey("Id")
                        .HasName("pk_installation");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("installation_key");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("installation_machine");

                    b.HasIndex("Search")
                        .HasDatabaseName("installation_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.HasIndex("SoftwareId")
                        .HasDatabaseName("installation_software");

                    b.ToTable("installation", null, t =>
                        {
                            t.HasCheckConstraint("ck_installation_backup", "backup in ('none', 'planned', 'active')");

                            t.HasCheckConstraint("ck_installation_environment", "environment in ('production', 'staging', 'development')");

                            t.HasCheckConstraint("ck_installation_logging", "logging in ('local', 'central')");

                            t.HasCheckConstraint("ck_installation_monitoring", "monitoring in ('none', 'external')");

                            t.HasCheckConstraint("ck_installation_role", "role in ('application', 'platform')");

                            t.HasCheckConstraint("ck_installation_status", "status in ('planned', 'active', 'retired')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Machines.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Arch")
                        .HasColumnType("text")
                        .HasColumnName("arch");

                    b.Property<string>("Cpu")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cpu");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Disk")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("disk");

                    b.Property<Guid?>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hostname");

                    b.Property<string>("Ipv4")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipv4");

                    b.Property<string>("Ipv6")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipv6");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<string>("Memory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("memory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Os")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("os");

                    b.Property<string>("Plan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plan");

                    b.Property<string>("PrivateIp")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("private_ip");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('simple', key || ' ' || name || ' ' || coalesce(hostname, '') || ' ' || coalesce(provider, '') || ' ' || coalesce(plan, '') || ' ' || coalesce(location, '') || ' ' || coalesce(os, '') || ' ' || coalesce(cpu, '') || ' ' || coalesce(memory, '') || ' ' || coalesce(disk, '') || ' ' || coalesce(ipv4, '') || ' ' || coalesce(ipv6, '') || ' ' || coalesce(private_ip, '') || ' ' || coalesce(ssh, '') || ' ' || description)", true);

                    b.Property<string>("Ssh")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ssh");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_machine");

                    b.HasIndex("HostId")
                        .HasDatabaseName("machine_host");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("machine_key");

                    b.HasIndex("Search")
                        .HasDatabaseName("machine_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.ToTable("machine", null, t =>
                        {
                            t.HasCheckConstraint("ck_machine_arch", "arch is null or arch in ('amd64', 'arm64')");

                            t.HasCheckConstraint("ck_machine_host", "host_id is null and kind <> 'vm' or kind = 'vm'");

                            t.HasCheckConstraint("ck_machine_kind", "kind in ('vps', 'dedicated', 'vm', 'local')");

                            t.HasCheckConstraint("ck_machine_not_its_own_host", "host_id is null or host_id <> id");

                            t.HasCheckConstraint("ck_machine_status", "status in ('planned', 'active', 'retired')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Pages.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_id");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('simple', title || ' ' || body)", true);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_page");

                    b.HasIndex("InstallationId")
                        .HasDatabaseName("page_on_installation")
                        .HasFilter("installation_id is not null");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("page_on_machine")
                        .HasFilter("machine_id is not null");

                    b.HasIndex("Search")
                        .HasDatabaseName("page_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("page_slug");

                    b.ToTable("page", null, t =>
                        {
                            t.HasCheckConstraint("ck_page_attached_to", "num_nonnulls(machine_id, installation_id) <= 1");

                            t.HasCheckConstraint("ck_page_kind", "kind in ('runbook', 'decision', 'note')");
                        });
                });

            modelBuilder.Entity("Hostingaffe.Domain.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Homepage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("homepage");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Repository")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repository");

                    b.Property<NpgsqlTsVector>("Search")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('simple', key || ' ' || name || ' ' || coalesce(image, '') || ' ' || coalesce(homepage, '') || ' ' || coalesce(repository, '') || ' ' || description)", true);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_software");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("software_key");

                    b.HasIndex("Search")
                        .HasDatabaseName("software_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Search"), "GIN");

                    b.ToTable("software", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Body")
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("IdentityId", "Key")
                        .HasName("pk_idempotency");

                    b.ToTable("idempotency", (string)null);
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Agent", b =>
                {
                    b.HasBaseType("Hostingaffe.Domain.Identities.Identity");

                    b.Property<DateTimeOffset?>("MetadataReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_reported_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");

                            t.HasCheckConstraint("ck_identity_user", "kind = 'user' and email is not null and normalized_email is not null and user_state in ('invited', 'active', 'deactivated') or kind = 'agent' and email is null and normalized_email is null and user_state is null and password_hash is null and bootstrap_exchanged_at is null");
                        });

                    b.HasDiscriminator().HasValue("agent");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.User", b =>
                {
                    b.HasBaseType("Hostingaffe.Domain.Identities.Identity");

                    b.Property<DateTimeOffset?>("BootstrapExchangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bootstrap_exchanged_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_state");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("identity_email")
                        .HasFilter("kind = 'user'");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_identity_kind", "kind in ('user', 'agent')");

                            t.HasCheckConstraint("ck_identity_owner", "kind = 'user' and owner_id is null or kind = 'agent' and owner_id is not null and not administrator");

                            t.HasCheckConstraint("ck_identity_user", "kind = 'user' and email is not null and normalized_email is not null and user_state in ('invited', 'active', 'deactivated') or kind = 'agent' and email is null and normalized_email is null and user_state is null and password_hash is null and bootstrap_exchanged_at is null");
                        });

                    b.HasDiscriminator().HasValue("user");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Deployments.Deployment", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_deployment_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Installations.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_installation");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_updated_by");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Files.File", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_file_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_file_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Installations.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_file_installation");

                    b.HasOne("Hostingaffe.Domain.Machines.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_file_machine");

                    b.OwnsMany("Hostingaffe.Domain.Files.FileRevision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("file_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Number")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("revision");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Number"));

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("by");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("content");

                            b1.Property<bool>("Executable")
                                .HasColumnType("boolean")
                                .HasColumnName("executable");

                            b1.Property<NpgsqlTsVector>("Search")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("tsvector")
                                .HasColumnName("search")
                                .HasComputedColumnSql("to_tsvector('simple', content)", true);

                            b1.HasKey("file_id", "Number")
                                .HasName("pk_file_revision");

                            b1.HasIndex("Search")
                                .HasDatabaseName("file_revision_search");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Search"), "GIN");

                            b1.ToTable("file_revision", (string)null);

                            b1.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                                .WithMany()
                                .HasForeignKey("By")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("fk_file_revision_by");

                            b1.WithOwner()
                                .HasForeignKey("file_id")
                                .HasConstraintName("fk_file_revision_file");
                        });

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Hostingaffe.Domain.History.HistoryEntry", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_history_actor");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.AgentMetadataReport", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Agent", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_identity_metadata_identity");

                    b.OwnsOne("Hostingaffe.Domain.Identities.AgentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("AgentMetadataReportId");

                            b1.Property<string>("Environment")
                                .HasJsonPropertyName("environment");

                            b1.Property<string>("Harness")
                                .HasJsonPropertyName("harness");

                            b1.Property<string>("Kind")
                                .HasJsonPropertyName("kind");

                            b1.Property<string>("Version")
                                .HasJsonPropertyName("version");

                            b1.HasKey("AgentMetadataReportId");

                            b1.ToTable("identity_metadata");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentMetadataReportId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.BrowserSession", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_browser_session_user");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.DeviceLogin", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_device_login_user");

                    b.HasOne("Hostingaffe.Domain.Identities.Token", null)
                        .WithMany()
                        .HasForeignKey("IssuedTokenId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_device_login_token");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.OneTimeSecret", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_one_time_secret_user");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Token", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_token_identity");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Installations.Installation", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_installation_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_installation_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Machines.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_installation_machine");

                    b.HasOne("Hostingaffe.Domain.Software", null)
                        .WithMany()
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_installation_software");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_installation_updated_by");

                    b.OwnsMany("Hostingaffe.Domain.Installations.Port", "Ports", b1 =>
                        {
                            b1.Property<Guid>("installation_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("port");

                            b1.Property<string>("Protocol")
                                .HasColumnType("text")
                                .HasColumnName("protocol");

                            b1.Property<string>("Scope")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("scope");

                            b1.HasKey("installation_id", "Number", "Protocol")
                                .HasName("pk_installation_port");

                            b1.ToTable("installation_port", null, t =>
                                {
                                    t.HasCheckConstraint("ck_installation_port_number", "port between 1 and 65535");

                                    t.HasCheckConstraint("ck_installation_port_protocol", "protocol in ('tcp', 'udp')");

                                    t.HasCheckConstraint("ck_installation_port_scope", "scope in ('public', 'private', 'internal')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("installation_id")
                                .HasConstraintName("fk_installation_port_installation");
                        });

                    b.OwnsMany("Hostingaffe.Domain.Installations.Secret", "Secrets", b1 =>
                        {
                            b1.Property<Guid>("installation_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Path")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("path");

                            b1.Property<NpgsqlTsVector>("Search")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("tsvector")
                                .HasColumnName("search")
                                .HasComputedColumnSql("to_tsvector('simple', name || ' ' || coalesce(path, ''))", true);

                            b1.HasKey("installation_id", "Name")
                                .HasName("pk_installation_secret");

                            b1.HasIndex("Search")
                                .HasDatabaseName("installation_secret_search");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("Search"), "GIN");

                            b1.ToTable("installation_secret", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("installation_id")
                                .HasConstraintName("fk_installation_secret_installation");
                        });

                    b.Navigation("Ports");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Machines.Machine", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_machine_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_machine_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Machines.Machine", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_machine_host");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_machine_updated_by");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Pages.Page", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_page_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_page_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Installations.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_page_installation");

                    b.HasOne("Hostingaffe.Domain.Machines.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_page_machine");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_page_updated_by");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Software", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_software_created_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_software_deleted_by");

                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_software_updated_by");
                });

            modelBuilder.Entity("Hostingaffe.Infrastructure.Persistence.IdempotencyRecord", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_identity");
                });

            modelBuilder.Entity("Hostingaffe.Domain.Identities.Agent", b =>
                {
                    b.HasOne("Hostingaffe.Domain.Identities.Identity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_identity_owner");

                    b.OwnsOne("Hostingaffe.Domain.Identities.AgentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("AgentId");

                            b1.Property<string>("Environment")
                                .HasJsonPropertyName("environment");

                            b1.Property<string>("Harness")
                                .HasJsonPropertyName("harness");

                            b1.Property<string>("Kind")
                                .HasJsonPropertyName("kind");

                            b1.Property<string>("Version")
                                .HasJsonPropertyName("version");

                            b1.HasKey("AgentId");

                            b1.ToTable("identity");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
